modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
issueTrackerURL="https://github.com/Andromander/Ornamental/issues" #optional
license="GNU Lesser General Public v3"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="ornamental" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ornamental" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Andromander/Ornamental/1.19.x/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ornamental" #optional
#logoFile="" #optional
credits="Androsa, or AlphaLeaf, your choice." #optional
authors="Androsa" #optional
description='''
Simple, versatile, the basic things to expand your experience.
Ornamental is a mod for your construction needs that you may have never known you needed. Decoration blocks like Stairs, Slabs, or Fences to cater for your every base needs to spruce up the look. Golems to protect and defend in their own ways.
This mod provides decorative blocks of usually absurd materials.
'''

[[dependencies.ornamental]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ornamental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,]"
    ordering="NONE"
    side="BOTH"